/**
 * Knowledge Graph Types
 * TypeScript interfaces matching the v3.2 JSON schema generated by the Python parser.
 *
 * v3.2 additions (backwards-compatible):
 *   - Track field on PhaseDefinition and Instruction — supports hybrid conditions
 *   - Patient Action on QuestionBranch, RedFlag, and Instruction — decisive routing
 *
 * v3.1 Condition + Classification taxonomy:
 *   - A file represents ONE Condition (e.g. "Cardiac Surgery", "Heart Failure").
 *   - The Condition contains one or more Classifications (e.g. CABG + VALVE;
 *     HFrEF + HFmrEF + HFpEF).
 *   - Phases live under each Classification.
 *   - Symptoms / Red Flags / Instructions carry `applicable_classifications`
 *     and are filtered at runtime based on the patient's classification.
 */

// ===== Metadata =====

export interface KnowledgeGraphMeta {
  source_file: string;
  generated_at: string;
  schema_version: string; // "v3.2" (or "v3.1" for older files)
  condition: {
    name: string;
    condition_type: 'episodic' | 'chronic' | 'hybrid';
    classifications: string[]; // list of classification labels
  };
  required_inputs: string[]; // e.g. ["classification", "surgery_date"]
}

// ===== Condition + Classification =====

export interface PhaseDefinition {
  name: string;
  day_range: [number, number | null]; // null = open-ended or ongoing
  day_range_type: 'fixed' | 'open' | 'ongoing';
  track?: 'episodic' | 'chronic' | 'hybrid'; // v3.2 — absent on v3.1 files
  focus: string;
  review: string;
  instruction_sheet: string;
  notes?: string;
}

export interface ClassificationDefinition {
  label: string; // e.g. "CABG"
  phases: {
    [phaseKey: string]: PhaseDefinition;
  };
}

export interface ConditionDefinition {
  name: string; // e.g. "Cardiac Surgery"
  condition_type: 'episodic' | 'chronic' | 'hybrid';
  trigger: string[]; // e.g. ["surgery_date"] or ["discharge_date", "enrollment_date"]
  phase_model: 'linear' | 'cyclical';
  classifications: {
    [classificationLabel: string]: ClassificationDefinition; // keyed by plain label e.g. "CABG"
  };
}

// ===== Symptoms =====

export interface PhaseOverride {
  action: string;
  note: string;
}

export interface QuestionBranch {
  label: string;
  risk_shift: number;
  escalate: boolean;
  patient_action?: string; // v3.2: ER_NOW | FACILITY_TODAY | NURSE_CALLBACK | SELF_MONITOR | —
  next: string | null;
}

export interface AssessmentQuestion {
  id: string;
  order: number;
  prompt: string;
  branches: {
    [key: string]: QuestionBranch;
  };
}

export interface Symptom {
  name: string;
  applicable_classifications: string[]; // ["ALL"] or list of classification labels
  applicable_phases: string[];
  base_severity: 'low' | 'moderate' | 'high';
  severity_score: number;
  phase_override: { [phaseKey: string]: PhaseOverride } | null;
  assessment_questions: AssessmentQuestion[];
  notes: string;
}

// ===== Red Flags =====

export interface RedFlag {
  id: string;
  symptom_id: string | null;
  trigger: string;
  applicable_classifications: string[]; // ["ALL"] or list of classification labels
  applicable_phases: string[];
  action: string;
  urgency: 'immediate' | 'urgent' | 'moderate';
  patient_action?: string; // v3.2: ER_NOW | FACILITY_TODAY | NURSE_CALLBACK
  context_note: string;
  rationale: string;
}

// ===== Instructions =====

export type InstructionCategory =
  | 'medication'
  | 'vitals'
  | 'diet'
  | 'exercise'
  | 'sleep'
  | 'stress'
  | 'symptom'
  | 'monitoring'
  | 'education'
  | 'other';

export interface Instruction {
  id: string;
  applicable_classifications: string[]; // ["ALL"] or list of classification labels
  applicable_phases: string[];
  track?: 'episodic' | 'chronic' | 'hybrid'; // v3.2 — absent on v3.1 files
  category: InstructionCategory;
  text: string;
  patient_action?: string; // v3.2: for threshold-type instructions only
  issued_at?: string;
  replaces: string | null;
  notes: string;
}

// ===== Scoring =====

export interface ScoreThreshold {
  min_score?: number;
  max_score?: number;
  action: string;
  patient_action?: string; // v3.2
}

export interface ScoringRules {
  escalate_override: string;
  phase_override: string;
}

export interface Scoring {
  thresholds: {
    [actionType: string]: ScoreThreshold;
  };
  rules: ScoringRules;
}

// ===== v3.3 — Facts, Rules, Settings (spec §4.5-4.7, Part 1b) =====

export type FactType = 'number' | 'boolean' | 'categorical';
export type FactArea =
  | 'vitals' | 'medication' | 'nutrition'
  | 'exercise' | 'appointment' | 'stress' | 'symptom';

/** A reportable patient data point. Keyed by machine_name in kg.facts; that key is not a field on this object. */
export interface Fact {
  display_name: string | null;
  area: FactArea;
  type: FactType;
  unit?: string;
  valid_for: string;
  valid_for_hours: number;
  required: boolean;
  applicable_classifications: string[];
  applicable_phases: string[];
  extraction_hint: string | null;
}

/**
 * AST emitted by the Python parser. TypeScript NEVER parses an expression — it only walks.
 * Call nodes use `func` as a secondary discriminant; switch on `kind` alone does not narrow
 * to a specific call variant — you must switch on `func` inside `case 'call':`.
 */
export type RuleAst =
  | { kind: 'and'; left: RuleAst; right: RuleAst }
  | { kind: 'or';  left: RuleAst; right: RuleAst }
  | { kind: 'not'; operand: RuleAst }
  | { kind: 'compare'; op: '>' | '>=' | '<' | '<=' | '==' | '!='; left: RuleAst; right: RuleAst }
  | { kind: 'fact'; name: string }
  | { kind: 'number'; value: number }
  | { kind: 'string'; value: string }
  | { kind: 'call'; func: 'delta' | 'count' | 'sum' | 'no_reading' | 'new_onset'; fact: string; window: string }
  | { kind: 'call'; func: 'persists'; ref: RuleAst; n: number; window: string }
  | { kind: 'call'; func: 'n_of'; n: number; refs: RuleAst[] };

export type RuleAction = 'REASSURE' | 'ADVISE' | 'ESCALATE';
/** v3.3 strict union. v3.2 fields (QuestionBranch, RedFlag, etc.) use loose `string` because they accepted '—' as a sentinel; v3.3 uses null instead. */
export type PatientAction = 'ER_NOW' | 'FACILITY_TODAY' | 'NURSE_CALLBACK' | 'SELF_MONITOR';

export interface Rule {
  rule_id: string;
  red_flag_id: string;
  order: number;
  expression: string;
  ast: RuleAst;
  action: RuleAction;
  patient_action: PatientAction | null;
  applicable_classifications: string[];
  applicable_phases: string[];
  reviewed_by?: string | null;
  reviewed_at?: string | null;
}

export interface KnowledgeBaseSettings {
  max_questions_per_checkin: number;
  min_days_between_checkins: string; // duration string, e.g. "3d" or "1w"
  checkin_trigger_stale_count: number;
  time_uncertainty_tolerance: number; // fraction of window (0–1), e.g. 0.25 = exclude readings with uncertainty > 25% of the rule window
  escalation_message?: string | null; // full replacement for the entire escalation message when set (not appended); translated per-locale; null when the KB has no Settings sheet or no row for this key, in which case the platform default is used
}

// ===== v3.3 — Rule Tests (spec §4.8, Part 1c) =====

export interface FactObservation {
  fact: string;
  value: number | boolean | string;
  offset_hours: number; // 0 = now; negative = the past
}

export interface RuleTest {
  test_id: string;
  rule_id: string;
  scenario: string; // what the SME reads
  observations: FactObservation[];
  expect: 'FIRES' | 'NOT_FIRES';
  notes?: string | null;
}

// ===== Complete Knowledge Graph =====

export interface KnowledgeGraph {
  meta: KnowledgeGraphMeta;
  condition: ConditionDefinition;
  symptoms: {
    [symptomId: string]: Symptom;
  };
  red_flags: RedFlag[];
  instructions: Instruction[]; // flat list — filter by applicable_phases + applicable_classifications
  scoring: Scoring;
  traversal: string[];
  // v3.3 additions — optional; absent on KBs without Sheets 7/8/9
  facts?: { [machineName: string]: Fact };
  rules?: Rule[];
  settings?: KnowledgeBaseSettings;
  warnings?: string[];
  // v3.3 addition — optional; absent on KBs without Sheet 10
  rule_tests?: RuleTest[];
}

// ===== Validation Results =====

export interface ValidationError {
  tab: string | null;
  row: number | null;
  column: string | null;
  error: string;
}

export interface ParseResult {
  valid: boolean;
  error_count: number;
  errors: ValidationError[];
  knowledge_graph: KnowledgeGraph | null;
}

// ===== Service Request/Response Types =====

export interface UploadKnowledgeGraphRequest {
  condition: string;  // Condition name derived from the parsed XLSX (e.g. "Cardiac Surgery")
  version: string;
  filePath: string;
}

export interface UploadKnowledgeGraphResponse {
  id: string;
  isValid: boolean;
  validationErrors: ValidationError[] | null;
  knowledgeGraph: KnowledgeGraph | null;
  status: 'DRAFT' | 'ACTIVE' | 'ARCHIVED';
}

export interface ActivateKnowledgeGraphRequest {
  id: string;
}

export interface ActivateKnowledgeGraphResponse {
  id: string;
  status: 'ACTIVE';
  previousActiveId?: string;
}

export interface ListKnowledgeGraphsQuery {
  condition?: string;
  status?: 'DRAFT' | 'ACTIVE' | 'ARCHIVED';
}

export interface KnowledgeGraphListItem {
  id: string;
  condition: string;          // e.g. "Cardiac Surgery"
  conditionType: 'episodic' | 'chronic' | 'hybrid' | null; // null for legacy KGs without condition_type
  classifications: string[];  // e.g. ["CABG", "VALVE"]
  version: string;
  status: 'DRAFT' | 'ACTIVE' | 'ARCHIVED';
  isValid: boolean;
  phaseNames: string[];
  createdAt: Date;
  updatedAt: Date;
}

/** Raw patient trigger dates passed to resolveDaysSinceStart() */
export interface TriggerDates {
  surgery_date?: Date;
  discharge_date?: Date;
  enrollment_date?: Date;
  diagnosis_date?: Date;
  lmp_date?: Date;
}

/** Result of resolveDaysSinceStart() */
export interface ResolvedPhaseInput {
  daysSinceStart: number;
  isReentry: boolean;
  triggerTypeUsed: string;
}
